###############################################################################
###                           Base Configuration                            ###
###############################################################################

# The minimum gas prices a validator is willing to accept for processing a
# transaction. A transaction's fees must meet the minimum of any denomination
# specified in this config (e.g. 0.25token1;0.0001token2).
minimum-gas-prices = "$APP__MIN_GAS_PRICE"

# default: the last 100 states are kept in addition to every 500th state; pruning at 10 block intervals
# nothing: all historic states will be saved, nothing will be deleted (i.e. archiving node)
# everything: all saved states will be deleted, storing only the current and previous state; pruning at 10 block intervals
# custom: allow pruning options to be manually specified through 'pruning-keep-recent', 'pruning-keep-every', and 'pruning-interval'
pruning = "$APP__PRUNE_METHOD"

# These are applied if and only if the pruning strategy is custom.
pruning-keep-recent = "$APP__PRUNE_KEEP_RECENT"
pruning-keep-every = "$APP__PRUNE_KEEP_EVERY"
pruning-interval = "$APP__PRUNE_INTERVAL"

# HaltHeight contains a non-zero block height at which a node will gracefully
# halt and shutdown that can be used to assist upgrades and testing.
#
# Note: Commitment of state will be attempted on the corresponding block.
halt-height = $APP__HALT_HEIGHT

# HaltTime contains a non-zero minimum block time (in Unix seconds) at which
# a node will gracefully halt and shutdown that can be used to assist upgrades
# and testing.
#
# Note: Commitment of state will be attempted on the corresponding block.
halt-time = $APP__HALT_TIME

# MinRetainBlocks defines the minimum block height offset from the current
# block being committed, such that all blocks past this offset are pruned
# from Tendermint. It is used as part of the process of determining the
# ResponseCommit.RetainHeight value during ABCI Commit. A value of 0 indicates
# that no blocks should be pruned.
#
# This configuration value is only responsible for pruning Tendermint blocks.
# It has no bearing on application state pruning which is determined by the
# "pruning-*" configurations.
#
# Note: Tendermint block pruning is dependant on this parameter in conunction
# with the unbonding (safety threshold) period, state pruning and state sync
# snapshot parameters to determine the correct minimum value of
# ResponseCommit.RetainHeight.
min-retain-blocks = $APP__MIN_RETAIN_BLOCKS

# InterBlockCache enables inter-block caching.
inter-block-cache = $APP__INTER_BLOCK_CACHE

# IndexEvents defines the set of events in the form {eventType}.{attributeKey},
# which informs Tendermint what to index. If empty, all events will be indexed.
#
# Example:
# ["message.sender", "message.recipient"]
index-events = [$APP__INDEX_EVENTS]

# IavlCacheSize set the size of the iavl tree cache. 
# Default cache size is 50mb.
iavl-cache-size = $APP__IAVL_CACHE_SIZE

###############################################################################
###                         Telemetry Configuration                         ###
###############################################################################

[telemetry]

# Prefixed with keys to separate services.
service-name = "$APP__TELEMETRY_KEY_PREFIX"

# Enabled enables the application telemetry functionality. When enabled,
# an in-memory sink is also enabled by default. Operators may also enabled
# other sinks such as Prometheus.
enabled = $APP__TELEMETRY_ENABLED

# Enable prefixing gauge values with hostname.
enable-hostname = $APP__TELEMETRY_HOSTNAME_ENABLED

# Enable adding hostname to labels.
enable-hostname-label = $APP__TELEMETRY_HOSTNAME__LABEL_ENABLED

# Enable adding service to labels.
enable-service-label = $APP__TELEMETRY_SERVICE_LABEL_ENABLED

# PrometheusRetentionTime, when positive, enables a Prometheus metrics sink.
prometheus-retention-time = $APP__TELEMETRY_PROMETHEUS_RET_TIME

# GlobalLabels defines a global set of name/value label tuples applied to all
# metrics emitted using the wrapper functions defined in telemetry package.
#
# Example:
# [["chain_id", "cosmoshub-1"]]
global-labels = $APP__TELEMETRY_GLOBAL_LABEL

###############################################################################
###                           API Configuration                             ###
###############################################################################

[api]

# Enable defines if the API server should be enabled.
enable = $APP__API_ENABLED

# Swagger defines if swagger documentation should automatically be registered.
swagger = $APP__API_SWAGGER_ENABLED

# Address defines the API server to listen on.
address = "$APP__API_LADDR"

# MaxOpenConnections defines the number of maximum open connections.
max-open-connections = $APP__API_MAX_CONN

# RPCReadTimeout defines the Tendermint RPC read timeout (in seconds).
rpc-read-timeout = $APP__API_RPC_R_TIMEOUT

# RPCWriteTimeout defines the Tendermint RPC write timeout (in seconds).
rpc-write-timeout = $APP__API_RPC_W_TIMEOUT

# RPCMaxBodyBytes defines the Tendermint maximum response body (in bytes).
rpc-max-body-bytes = $APP__API_RPC_MAX_BODYSIZE

# EnableUnsafeCORS defines if CORS should be enabled (unsafe - use it at your own risk).
enabled-unsafe-cors = $APP__API_UNSAFE_CORES_ENABLED

###############################################################################
###                           Rosetta Configuration                         ###
###############################################################################

[rosetta]

# Enable defines if the Rosetta API server should be enabled.
enable = $APP__ROSETTA_ENBALED

# Address defines the Rosetta API server to listen on.
address = "$APP__ROSETTA_LADDR"

# Network defines the name of the blockchain that will be returned by Rosetta.
blockchain = "$APP__ROSETTA_BLOCKCHAIN_NAME"

# Network defines the name of the network that will be returned by Rosetta.
network = "$APP__ROSETTA_NETWORK_NAME"

# Retries defines the number of retries when connecting to the node before failing.
retries = $APP__ROSETTA_RETRY_COUNT

# Offline defines if Rosetta server should run in offline mode.
offline = $APP__ROSETTA_OFFLINE_ENABLED

###############################################################################
###                           gRPC Configuration                            ###
###############################################################################

[grpc]

# Enable defines if the gRPC server should be enabled.
enable = $APP__GRPC_ENABLED

# Address defines the gRPC server address to bind to.
address = "$APP__GRPC_LADDR"

###############################################################################
###                        gRPC Web Configuration                           ###
###############################################################################

[grpc-web]

# GRPCWebEnable defines if the gRPC-web should be enabled.
# NOTE: gRPC must also be enabled, otherwise, this configuration is a no-op.
enable = $APP__GRPC_WEB_ENABLED

# Address defines the gRPC-web server address to bind to.
address = "$APP__GRPC_WEB_LADDR"

# EnableUnsafeCORS defines if CORS should be enabled (unsafe - use it at your own risk).
enable-unsafe-cors = $APP__GRPC_WEB_UNSAFE_CORS_ENABLED

###############################################################################
###                        State Sync Configuration                         ###
###############################################################################

# State sync snapshots allow other nodes to rapidly join the network without replaying historical
# blocks, instead downloading and applying a snapshot of the application state at a given height.
[state-sync]

# snapshot-interval specifies the block interval at which local state sync snapshots are
# taken (0 to disable). Must be a multiple of pruning-keep-every.
snapshot-interval = $APP__STATESYNC_INTERVAL

# snapshot-keep-recent specifies the number of recent snapshots to keep and serve (0 to keep all).
snapshot-keep-recent = $APP__STATESYNC_KEEP_RECENT

[wasm]
# This is the maximum sdk gas (wasm and storage) that we allow for any x/wasm "smart" queries
query_gas_limit = $APP__WASM_QUERY_GAS_LIMIT
# This is the number of wasm vm instances we keep cached in memory for speed-up
# Warning: this is currently unstable and may lead to crashes, best to keep for 0 unless testing locally
lru_size = $APP__WASM_WASMVM_CACHE
