# This is a TOML config file.
# For more information, see https://github.com/toml-lang/toml

###############################################################################
###                           Client Configuration                            ###
###############################################################################

# The network chain ID
chain-id = "$CLIENT__CHAIN_ID"
# The keyring's backend, where the keys are stored (os|file|kwallet|pass|test|memory)
keyring-backend = "$CLIENT__KEYRING_BACKEND"
# CLI output format (text|json)
output = "$CLIENT__CLI_OUTPUT"
# <host>:<port> to Tendermint RPC interface for this chain
node = "$CLIENT__TENDERMINT_RPC_ADDR"
# Transaction broadcasting mode (sync|async|block)
broadcast-mode = "$CLIENT__BROADCAST_MODE"

## Added in v15.2 https://github.com/osmosis-labs/osmosis/pull/5020
# Amount of gas per transaction
gas = "$CLIENT__GAS"
# Price per unit of gas
gas-prices = "$CLIENT__GAS_PRICES"
gas-adjustment = "$CLIENT__GAS_ADJUSTMENT"