version: '3'

services:
  terra:
    image: chainroot/terra:latest
    restart: always
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    env_file: .env
    ports:
      - 26656:26656
      - 26657:26657
    volumes:
      - ./data:/terra/.terra
