version: '3'

services:
  stride:
    image: chainroot/stride:v17.0.0
    restart: always
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    ports:
      - 26656:26656
      - 26657:26657
    # In order to persist data
    volumes:
      - ./data:/stride/.stride
