name: Automated Version Update Check

on:
  schedule:
    - cron: '*/15 * * * *' 

permissions:
  pull-requests: write
  repository-projects: write

jobs:
  update-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: check versions
        run: make checkversion      

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: "chore: updated versions"
          branch: main

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          delete-branch: true
          base: main
          head: bot-update-branch
          title: "chore: automated update on versions"
          body: "This is an automated update by bot."
